class MyString:
    capacity_: int
    size_: int

    def __init__(self, value: str = ...) -> None: ...
    def clear(self) -> None: ...
    def shrink_to_fit(self) -> None: ...
    def c_str(self) -> str: ...
    def size(self) -> int: ...
    def capacity(self) -> int: ...
    def empty(self) -> bool: ...
    def insert(self, index: int, count_or_source: int | str, char_or_count: str | int = ..., count: int = ...) -> None: ...
    def append(self, value_or_count: str | int, char: str = ..., count: int = ..., source_index: int = ...) -> None: ...
    def erase(self, index: int, count: int) -> None: ...
    def replace(self, index: int, count: int, source: str, source_index_or_count: int = ..., source_count: int = ...) -> None: ...
    def substr(self, index: int, count: int = ...) -> MyString: ...
    def compare(self, other: MyString) -> int: ...
    def find(self, source: str, index: int = ...) -> int: ...

    def __getitem__(self, index: int) -> str: ...
    def __setitem__(self, index: int, value: str) -> None: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __add__(self, value: str) -> MyString: ...
    def __iadd__(self, value: str) -> MyString: ...


def pstr(value: MyString) -> None: ...
