apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-users-secret
  namespace: app
type: Opaque
data:
  users.json: e30=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-secret-app
  namespace: app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-secret-reader-writer
  namespace: app
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["flask-users-secret"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-secret-reader-writer-binding
  namespace: app
subjects:
  - kind: ServiceAccount
    name: flask-secret-app
    namespace: app
roleRef:
  kind: Role
  name: flask-secret-reader-writer
  apiGroup: rbac.authorization.k8s.io
